[package]
name = "cli"
version = "0.0.1"
authors = ["Phraeyll <Phraeyll@users.noreply.github.com>"]
edition = "2018"

[dependencies]
clap = "^2.32"
point-mass-ballistics = { path = "../point-mass-ballistics" }

[[bin]]
name = "cli"
