[package]
name = "rballistics-cli"
version = "0.0.1"
authors = ["Phraeyll <Phraeyll@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rballistics-flat = { path = "../flat" }
approx = "^0.3"

[[bin]]
name = "rballistics-cli"
