[package]
name = "rballistics-cli"
version = "0.0.1"
authors = ["Phraeyll <Phraeyll@users.noreply.github.com>"]
edition = "2018"

[dependencies]
clap = "^2.32"
rballistics-flat = { path = "../flat" }
ordered-float = "^1.0"

[[bin]]
name = "rballistics-cli"
